# R 시작하기 {#sec-R-start}

## 연습문제 {.unnumbered}

**2.** 다음의 숫자형 벡터를 만들어 보자.

    -  -5  -4  -3 -2  -1  0  1  2  3   4  5

```{r}
       -5:5
```
    
    -   5  4  3  2  1  0  -1  -2   -3  -4  -5

```{r}
        5:-5
```
    
    -   1  3  5  7  9  2  4  6  8

```{r}
        c(seq(1, 7, by = 2), seq(2, 8, by = 2))
```
    
    -   1  2  2  3  3   3   4   4   4  4   

```{r}
        rep(1:4, times = 1:4)
```
    
    -  1  2   3   1  2  3  1  2  3 

```{r}
       rep(1:3, times = 3)
```
    
**3.** 다음의 문자형 벡터를 만들어 보자. 

    -  "a"  "a"  "b"  "b"  "b" 

```{r}
       rep(c("a", "b"), times = c(2, 3))
```
    
    -   "a1"  "a2"  "a3"  "a4"  "a5" 

```{r}
        paste0("a", 1:5)
```
    
    -   "aa"  "ba"  "ca"  "ab"  "bb"  "cb"  "ac"  "bc"  "cc"       

```{r}
        paste0(rep(c("a", "b", "c"), times = 2), rep(c("a", "b", "c"), each = 3))
```


**4.** 벡터 `letters`는 영문 소문자로 이루어져 있는 문자형 벡터이다. 벡터 `letters`를 이용해서 다음의 벡터 `a1`을 만들어 보자. 
   
```{r}
   a1 <- paste(letters, 1:length(letters))
```

**5.** 벡터 `a1`은 영문자와 숫자 사이에 빈칸이 있다. 다음과 같이 영문자와 숫자 사이에 빈칸이 없는 벡터 `a2`를 벡터 `letters`를 이용해서 만들어 보자. 
    
```{r}
   a2 <- paste0(letters, 1:length(letters))
```








